# Generated by Django 5.1.11 on 2026-02-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=255, verbose_name='Category Name')),
                ('category', models.ForeignKey(blank=True, help_text='The parent category for this category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'indexes': [models.Index(fields=['category', 'name'], name='category_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_category_name_per_parent')],
            },
        ),
    ]
