# Generated by Django 5.1.11 on 2026-02-28 06:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articleindexpage_articlepage_articlepagetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='news.articlepage'),
        ),
    ]
