# Generated by Django 5.1.11 on 2026-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articlepagetag_content_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
