# Generated by Django 5.1.11 on 2026-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_printsession_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsession',
            name='passkey_hash',
            field=models.CharField(max_length=255),
        ),
    ]
