# Generated by Django 5.1.11 on 2026-02-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_printsession_passkey_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printsession',
            name='code',
        ),
    ]
