# Generated by Django 5.1.11 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_printsession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsession',
            name='passkey',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
