# Generated by Django 5.1.11 on 2026-02-25 14:50

import apps.uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_printsession_passkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='printsession',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='printsession',
            name='passkey_hash',
        ),
        migrations.AddField(
            model_name='printsession',
            name='access_code',
            field=models.CharField(default=apps.uploads.models.generate_session_code, max_length=6, unique=True),
        ),
    ]
