# Generated by Django 5.1.11 on 2026-05-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_printsession_options_and_more'),
        ('users', '0004_user_account_type_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='users.profile'),
        ),
    ]
