# Generated by Django 5.1.11 on 2026-05-03 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_printsession_customer'),
        ('users', '0004_user_account_type_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='printsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('printed', 'Printed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('file_uploaded', 'File Uploaded'), ('printed', 'Printed'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=50)),
                ('access_code', models.CharField(max_length=6)),
                ('customer_snapshot', models.JSONField(blank=True, default=dict)),
                ('session_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='uploads.printsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
